version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: MonolithDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 210199**
    expose:
      - "5432"
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"

  api:
    restart: always
    container_name: monolyth-api-container
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
 #   command: ["dotnet", "ef", "database update"]
